name: tfcmt --skip-no-changes test

on:
  pull_request:
    paths:
      - "tf/**/*.tf"
      - ".github/workflows/tfcmt.yaml"

jobs:
  terraform-plan:
    permissions:
      contents: read
      pull-requests: write

    continue-on-error: true
    strategy:
      matrix:
        directory:
          - tf/staging-prepear
          - tf/staging
          - tf/production-prepear
          - tf/production

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "${{ matrix.directory }}"
    steps:
      - name: "checkout"
        uses: actions/checkout@v3

      - name: "setup terraform ${TERRAFORM_VERSION}"
        env:
          TERRAFORM_VERSION: 1.0.0
        uses: hashicorp/setup-terraform@v2
        with:
            terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: "install tfcmt ${TFCMT_VERSION}"
        env:
          TFCMT_VERSION: v4.4.3
        run: |
          wget "https://github.com/suzuki-shunsuke/tfcmt/releases/download/${TFCMT_VERSION}/tfcmt_linux_amd64.tar.gz" -O /tmp/tfcmt.tar.gz
          tar xzf /tmp/tfcmt.tar.gz -C /tmp
          mv /tmp/tfcmt /usr/local/bin
          tfcmt --version

      - name: "terraform init ${{ matrix.directory }}"
        run: terraform init

      - name: "terraform validate ${{ matrix.directory }}"
        run: terraform validate -no-color

      - name: "terraform plan ${{ matrix.directory }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # --skip-no-changes 未指定 -
        run: tfcmt --var target:${{ matrix.directory }} plan --patch -- terraform plan -no-color -input=false
